Homework Test Results

TestCase                                Result
================================================================
test1.py                                Crashed due to signal 1:
Traceback (most recent call last):
  File "/tmp/tmp46orua93/test1.py", line 46, in <module>
  File "/tmp/tmp46orua93/test1.py", line 40, in main
  File ".../05.py", line 2, in reachNumber
NameError: name 'v1' is not defined


test2.py                                Crashed due to signal 1:
Traceback (most recent call last):
  File "/tmp/tmp46orua93/test2.py", line 47, in <module>
  File "/tmp/tmp46orua93/test2.py", line 40, in main
  File ".../05.py", line 2, in reachNumber
NameError: name 'v1' is not defined


================================================================
Result: 0/10

Key:
	Failed to Compile: Your submission did not compile due to a syntax or naming error
	Compiled with warnings: Your submission uses unchecked or unsafe operations
	Crashed due to signal SIGNAL_CODE: Your submission threw an uncaught exception.
	All signal error codes are described here: https://man7.org/linux/man-pages/man7/signal.7.html
	Exceeded Time Limit: Your submission took too much time to run (probably an infinite loop)
